### ISSUE TITLE
pyarrow.lib.ArrowInvalid: Field named openfe_index is not found

### ISSUE THREAD

**Issue by InPatience** [IIIS-Li-Group/OpenFE#19]
Hi, I have a problem when I try OpenFE on my own dataset.  

```
Traceback (most recent call last):
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/openfe/openfe.py", line 669, in _calculate_and_evaluate_multiprocess
    data = pd.read_feather(self.tmp_save_path, columns=list(base_features)).set_index('openfe_index')
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/pandas/io/feather_format.py", line 127, in read_feather
    return feather.read_feather(
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/pyarrow/feather.py", line 226, in read_feather
    return (read_table(
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/pyarrow/feather.py", line 262, in read_table
    table = reader.read_names(columns)
  File "pyarrow/_feather.pyx", line 114, in pyarrow._feather.FeatherReader.read_names
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Field named openfe_index is not found
```
It looks like the function `_calculate_and_evaluate_multiprocess` is trying to read `train_x ` at
` data = pd.read_feather(self.tmp_save_path, columns=list(base_features)).set_index('openfe_index')`
while `train_x ` does not have a column named 'openfe_index', which is added to the list variable `base_features`.

I am not clear about the reason of adding extra column name 'openfe_index'. But when I running the example code, there is no such problem. My input data has been checked. All my Input are pandas.Dataframe and have no columns type problem.

**Comment by ZhangTP1996** [comment]
The reason for adding 'openfe_index' is simply to assign a name to the index, so that we can set the index when reloading the data from temporary self.tmp_save_path. I cannot guess a reason of this bug given little information. Could you please provide a reproducible example including codes and datasets?

**Comment by InPatience** [comment]
Thanks for your response. It turns out that the method `process_and_save_data(self)` cannot successfully handle dataframe with _MultiIndex_ .  The multiindexed will be reset to more than one column with MultiIndex.names.

```
    def process_and_save_data(self):
        self.data.index.name = 'openfe_index'
        self.data.reset_index().to_feather(self.tmp_save_path)
```

**Comment by ZhangTP1996** [comment]
Thank you for reporting this bug! I'll keep this issue open as a reminder to handle dataframes with MultiIndex.
