### ISSUE TITLE
california housing example

### ISSUE THREAD

**Issue by StevenFurious** [IIIS-Li-Group/OpenFE#20]
I run the sample code 'california housing' and received the following issues:

Traceback (most recent call last):
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/openfe/openfe.py", line 610, in _evaluate
    gbm.fit(train_x, train_y, init_score=train_init,
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/sklearn.py", line 818, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/sklearn.py", line 683, in fit
    self._Booster = train(params, train_set,
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/basic.py", line 2229, in __init__
    train_set.construct()
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/basic.py", line 1468, in construct
    self._lazy_init(self.data, label=self.label,
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/basic.py", line 1294, in _lazy_init
    self.set_init_score(init_score)
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/basic.py", line 1843, in set_init_score
    init_score = list_to_1d_numpy(init_score, np.float64, name='init_score')
  File "/Users/quanminghang/opt/anaconda3/envs/SQquant/lib/python3.8/site-packages/lightgbm/basic.py", line 164, in list_to_1d_numpy
    raise TypeError("Wrong type({0}) for {1}.\n"
TypeError: Wrong type(DataFrame) for init_score.
It should be list, numpy 1-D array or pandas Series

**Comment by ZhangTP1996** [comment]
I guess it is probably due to the version of LightGBM. What is your version? lgb==3.3.2 should be able to run the code.

**Comment by StevenFurious** [comment]
I installed the lightgbm version 3.3.2, and run the example in Jupyter on MacOS 13.
It seems that another issue occured: 
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.


<img width="892" alt="截屏2023-02-24 00 51 07" src="https://user-images.githubusercontent.com/109652745/220974905-6820ede3-88ad-472b-b1cc-796c4368c64b.png">

**Comment by StevenFurious** [comment]
n_jobs =1 doens't work either.

**Comment by ZhangTP1996** [comment]
Hi, why is this issue closed? Is the problem solved?

**Comment by StevenFurious** [comment]
Hi,


Yes, I figured out it is all related to lightgbm packages. I have tried:
pip install lightgbm
brew install lightgbm
conda install -c conda-forge lightgbm


'conda install -c conda-forge lightgbm' solves the problem.




| |
stevenquan90
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/24/2023 11:40 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [IIIS-Li-Group/OpenFE] california housing example (Issue #20) |

Hi, why is this issue closed? Is the problem solved?
