### ISSUE TITLE
Exception when `-` in column name during transform

### ISSUE THREAD

**Issue by Innixma** [IIIS-Li-Group/OpenFE#30]
The following example on AdultIncome dataset fails due to `-` in feature names (for example, `capital-gain`).

```python3
import pandas as pd
from openfe import OpenFE, transform


if __name__ == '__main__':
    label = 'class'
    train_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
    test_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')

    train_y = train_data[[label]]
    train_x = train_data.drop(columns=[label])
    test_y = test_data[[label]]
    test_x = test_data.drop(columns=[label])

    train_x = train_x[['age', 'sex', 'capital-gain']]
    test_x = test_x[['age', 'sex', 'capital-gain']]

    # FIXME: Uncomment to avoid exception
    # train_x.columns = ['age', 'sex', 'capital']
    # test_x.columns = ['age', 'sex', 'capital']

    ofe = OpenFE()
    features = ofe.fit(data=train_x, label=train_y, n_jobs=4)
    train_x, test_x = transform(X_train=train_x, X_test=test_x, new_features_list=features, n_jobs=4)
```

The error looks like this:

```
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openfe/utils.py", line 102, in _cal
    _data = pd.read_feather('./openfe_tmp_data.feather', columns=base_features).set_index('openfe_index')
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pandas/io/feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pyarrow/feather.py", line 226, in read_feather
    return (read_table(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pyarrow/feather.py", line 262, in read_table
    table = reader.read_names(columns)
  File "pyarrow/_feather.pyx", line 114, in pyarrow._feather.FeatherReader.read_names
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Field named gain is not found

Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openfe/utils.py", line 102, in _cal
    _data = pd.read_feather('./openfe_tmp_data.feather', columns=base_features).set_index('openfe_index')
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pandas/io/feather_format.py", line 132, in read_feather
    return feather.read_feather(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pyarrow/feather.py", line 226, in read_feather
    return (read_table(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/pyarrow/feather.py", line 262, in read_table
    table = reader.read_names(columns)
  File "pyarrow/_feather.pyx", line 114, in pyarrow._feather.FeatherReader.read_names
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Field named capital is not found

```

Proposed Fix:

Either add support for feature names with `-`, or sanitize internally the column names to avoid the error.

You may also want to be wary of the edge-case scenario with 3 feature names : `A`, `B`, `A-B`

**Comment by LeoZWT** [comment]
Yeah, I found that mistake too.
